/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RSAKeyPairGenerator */

#ifndef _Included_RSAKeyPairGenerator
#define _Included_RSAKeyPairGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RSAKeyPairGenerator
 * Method:    generateKeyPair0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RSAKeyPairGenerator_generateKeyPair0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
