/*
 * Copyright (C) Canonical, Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OpenSSLPBKDF2Spi */

#ifndef _Included_OpenSSLPBKDF2Spi
#define _Included_OpenSSLPBKDF2Spi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenSSLPBKDF2Spi
 * Method:    generateKey0
 * Signature: ([C[BI)LOpenSSLPBKDF2Spi/PBKDF2SecretKey;
 */
JNIEXPORT jbyteArray JNICALL Java_com_canonical_openssl_kdf_OpenSSLPBKDF2_generateSecret0
  (JNIEnv *, jobject, jcharArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
