/*
 * Copyright (C) Canonical, Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_canonical_openssl_keyagreement_OpenSSLKeyAgreement */

#ifndef _Included_com_canonical_openssl_keyagreement_OpenSSLKeyAgreement
#define _Included_com_canonical_openssl_keyagreement_OpenSSLKeyAgreement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_canonical_openssl_keyagreement_OpenSSLKeyAgreement
 * Method:    cleanupNativeMemory0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_canonical_openssl_keyagreement_OpenSSLKeyAgreement_cleanupNativeMemory0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_canonical_openssl_keyagreement_OpenSSLKeyAgreement
 * Method:    engineInit0
 * Signature: (I[B)J
 */
JNIEXPORT jlong JNICALL Java_com_canonical_openssl_keyagreement_OpenSSLKeyAgreement_engineInit0
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_canonical_openssl_keyagreement_OpenSSLKeyAgreement
 * Method:    engineDoPhase0
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_canonical_openssl_keyagreement_OpenSSLKeyAgreement_engineDoPhase0
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_canonical_openssl_keyagreement_OpenSSLKeyAgreement
 * Method:    engineGenerateSecret0
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_canonical_openssl_keyagreement_OpenSSLKeyAgreement_engineGenerateSecret0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
