/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_canonical_openssl_mac_OpenSSLMAC */

#ifndef _Included_com_canonical_openssl_mac_OpenSSLMAC
#define _Included_com_canonical_openssl_mac_OpenSSLMAC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_canonical_openssl_mac_OpenSSLMAC
 * Method:    cleanupNativeMemory0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_canonical_openssl_mac_OpenSSLMAC_cleanupNativeMemory0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_canonical_openssl_mac_OpenSSLMAC
 * Method:    doInit0
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BI[B)J
 */
JNIEXPORT jlong JNICALL Java_com_canonical_openssl_mac_OpenSSLMAC_doInit0
  (JNIEnv *, jobject, jstring, jstring, jstring, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_canonical_openssl_mac_OpenSSLMAC
 * Method:    getMacLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_canonical_openssl_mac_OpenSSLMAC_getMacLength
  (JNIEnv *, jobject);

/*
 * Class:     com_canonical_openssl_mac_OpenSSLMAC
 * Method:    doUpdate0
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_canonical_openssl_mac_OpenSSLMAC_doUpdate0
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_canonical_openssl_mac_OpenSSLMAC
 * Method:    doFinal0
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_canonical_openssl_mac_OpenSSLMAC_doFinal0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
