/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OpenSSLMD */

#ifndef _Included_OpenSSLMD
#define _Included_OpenSSLMD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenSSLMD
 * Method:    doInit0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_canonical_openssl_md_OpenSSLMD_doInit0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     OpenSSLMD
 * Method:    doUpdate0
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_canonical_openssl_md_OpenSSLMD_doUpdate0
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     OpenSSLMD
 * Method:    doFinal0
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_canonical_openssl_md_OpenSSLMD_doFinal0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
