/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OpenSSLCipherSpi */

#ifndef _Included_OpenSSLCipherSpi
#define _Included_OpenSSLCipherSpi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenSSLCipherSpi
 * Method:    createContext0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_OpenSSLCipherSpi_createContext0
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     OpenSSLCipherSpi
 * Method:    doInit0
 * Signature: ([BII[B[BI)V
 */
JNIEXPORT void JNICALL Java_OpenSSLCipherSpi_doInit0
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jbyteArray, jint);

/*
 * Class:     OpenSSLCipherSpi
 * Method:    doUpdate0
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_OpenSSLCipherSpi_doUpdate0
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     OpenSSLCipherSpi
 * Method:    doFinal0
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_OpenSSLCipherSpi_doFinal0
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
