/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_canonical_openssl_signature_OpenSSLSignature */

#ifndef _Included_com_canonical_openssl_signature_OpenSSLSignature
#define _Included_com_canonical_openssl_signature_OpenSSLSignature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_canonical_openssl_signature_OpenSSLSignature
 * Method:    cleanupNativeMemory0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_canonical_openssl_signature_OpenSSLSignature_cleanupNativeMemory0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_canonical_openssl_signature_OpenSSLSignature
 * Method:    engineInitSign0
 * Signature: (Ljava/lang/String;Lcom/canonical/openssl/key/OpenSSLPrivateKey;Lcom/canonical/openssl/signature/OpenSSLSignature/Params;)J
 */
JNIEXPORT jlong JNICALL Java_com_canonical_openssl_signature_OpenSSLSignature_engineInitSign0
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     com_canonical_openssl_signature_OpenSSLSignature
 * Method:    engineInitVerify0
 * Signature: (Ljava/lang/String;Lcom/canonical/openssl/key/OpenSSLPublicKey;Lcom/canonical/openssl/signature/OpenSSLSignature/Params;)J
 */
JNIEXPORT jlong JNICALL Java_com_canonical_openssl_signature_OpenSSLSignature_engineInitVerify0
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     com_canonical_openssl_signature_OpenSSLSignature
 * Method:    engineSign0
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_canonical_openssl_signature_OpenSSLSignature_engineSign0
  (JNIEnv *, jobject);

/*
 * Class:     com_canonical_openssl_signature_OpenSSLSignature
 * Method:    engineUpdate0
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_canonical_openssl_signature_OpenSSLSignature_engineUpdate0
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_canonical_openssl_signature_OpenSSLSignature
 * Method:    engineVerify0
 * Signature: ([BII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_canonical_openssl_signature_OpenSSLSignature_engineVerify0
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
