/*
 * Copyright (C) Canonical, Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RSAKeyPairGenerator */

#ifndef _Included_RSAKeyPairGenerator
#define _Included_RSAKeyPairGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RSAKeyPairGenerator
 * Method:    generateKeyPair0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RSAKeyPairGenerator_generateKeyPair0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
