/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EdDSAPrivateKey */

#ifndef _Included_EdDSAPrivateKey
#define _Included_EdDSAPrivateKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EdDSAPrivateKey
 * Method:    readPrivKeyFromPem0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_EdDSAPrivateKey_readPrivKeyFromPem0
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
