/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EdDSAPublicKey */

#ifndef _Included_EdDSAPublicKey
#define _Included_EdDSAPublicKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EdDSAPublicKey
 * Method:    readPubKeyFromPem0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_EdDSAPublicKey_readPubKeyFromPem0
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
