/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OpenSSLSignatureSpi */

#ifndef _Included_OpenSSLSignatureSpi
#define _Included_OpenSSLSignatureSpi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenSSLSignatureSpi
 * Method:    engineSignInit
 * Signature: (Ljava/lang/String;LOpenSSLPublicKey;LOpenSSLSignatureSpi/Params;)J
 */
JNIEXPORT jlong JNICALL Java_OpenSSLSignatureSpi_engineInitSign
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     OpenSSLSignatureSpi
 * Method:    engineVerifyInit
 * Signature: (Ljava/lang/String;LOpenSSLPrivateKey;LOpenSSLSignatureSpi/Params;)J
 */
JNIEXPORT jlong JNICALL Java_OpenSSLSignatureSpi_engineInitVerify
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     OpenSSLSignatureSpi
 * Method:    engineSign0
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_OpenSSLSignatureSpi_engineSign0
  (JNIEnv *, jobject);

/*
 * Class:     OpenSSLSignatureSpi
 * Method:    engineUpdate0
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_OpenSSLSignatureSpi_engineUpdate0
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     OpenSSLSignatureSpi
 * Method:    engineVerify0
 * Signature: ([BII)Z
 */
JNIEXPORT jboolean JNICALL Java_OpenSSLSignatureSpi_engineVerify0
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
