/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OpenSSLKeyAgreementSpi */

#ifndef _Included_OpenSSLKeyAgreementSpi
#define _Included_OpenSSLKeyAgreementSpi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenSSLKeyAgreementSpi
 * Method:    engineInit0
 * Signature: (I[B)J
 */
JNIEXPORT long JNICALL Java_OpenSSLKeyAgreementSpi_engineInit0
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     OpenSSLKeyAgreementSpi
 * Method:    engineDoPhase0
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_OpenSSLKeyAgreementSpi_engineDoPhase0
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     OpenSSLKeyAgreementSpi
 * Method:    engineGenerateSecret0
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_OpenSSLKeyAgreementSpi_engineGenerateSecret0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
