/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_canonical_openssl_OpenSSLDrbg */

#ifndef _Included_com_canonical_openssl_OpenSSLDrbg
#define _Included_com_canonical_openssl_OpenSSLDrbg
#ifdef __cplusplus
extern "C" {
#endif
#undef com_canonical_openssl_OpenSSLDrbg_serialVersionUID
#define com_canonical_openssl_OpenSSLDrbg_serialVersionUID 3905348978240129619LL
#undef com_canonical_openssl_OpenSSLDrbg_multiplier
#define com_canonical_openssl_OpenSSLDrbg_multiplier 25214903917LL
#undef com_canonical_openssl_OpenSSLDrbg_addend
#define com_canonical_openssl_OpenSSLDrbg_addend 11LL
#undef com_canonical_openssl_OpenSSLDrbg_mask
#define com_canonical_openssl_OpenSSLDrbg_mask 281474976710655LL
#undef com_canonical_openssl_OpenSSLDrbg_DOUBLE_UNIT
#define com_canonical_openssl_OpenSSLDrbg_DOUBLE_UNIT 1.1102230246251565E-16
#undef com_canonical_openssl_OpenSSLDrbg_serialVersionUID
#define com_canonical_openssl_OpenSSLDrbg_serialVersionUID 4940670005562187LL
/*
 * Class:     com_canonical_openssl_OpenSSLDrbg
 * Method:    init
 * Signature: (Ljava/lang/String;IZZ[B)J
 */
JNIEXPORT jlong JNICALL Java_com_canonical_openssl_OpenSSLDrbg_init
  (JNIEnv *, jobject, jstring, jint, jboolean, jboolean, jbyteArray);

/*
 * Class:     com_canonical_openssl_OpenSSLDrbg
 * Method:    nextBytes0
 * Signature: ([BIZ[B)V
 */
JNIEXPORT void JNICALL Java_com_canonical_openssl_OpenSSLDrbg_nextBytes0
  (JNIEnv *, jobject, jbyteArray, jint, jboolean, jbyteArray);

/*
 * Class:     com_canonical_openssl_OpenSSLDrbg
 * Method:    reseed0
 * Signature: ([BZ[B)V
 */
JNIEXPORT void JNICALL Java_com_canonical_openssl_OpenSSLDrbg_reseed0
  (JNIEnv *, jobject, jbyteArray, jboolean, jbyteArray);

/*
 * Class:     com_canonical_openssl_OpenSSLDrbg
 * Method:    generateSeed0
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_canonical_openssl_OpenSSLDrbg_generateSeed0
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
