/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OpenSSLPBKDF2Spi */

#ifndef _Included_OpenSSLPBKDF2Spi
#define _Included_OpenSSLPBKDF2Spi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenSSLPBKDF2Spi
 * Method:    generateKey0
 * Signature: ([C[BI)LOpenSSLPBKDF2Spi/PBKDF2SecretKey;
 */
JNIEXPORT jbyteArray JNICALL Java_OpenSSLPBKDF2Spi_generateSecret0
  (JNIEnv *, jobject, jcharArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
